In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

seeds= pd.read_csv('./data/seeds_dataset.txt', sep='\t')
seeds.head(5)

f1     f2      f3     f4     f5     f6     f7  t1
0  15.26  14.84  0.8710  5.763  3.312  2.221  5.220   1
1  14.88  14.57  0.8811  5.554  3.333  1.018  4.956   1
2  14.29  14.09  0.9050  5.291  3.337  2.699  4.825   1
3  13.84  13.94  0.8955  5.324  3.379  2.259  4.805   1
4  16.14  14.99  0.9034  5.658  3.562  1.355  5.175   1

In [2]:
seeds.describe()

f1          f2          f3          f4          f5          f6  \
count  210.000000  210.000000  210.000000  210.000000  210.000000  210.000000   
mean    14.847524   14.559286    0.870999    5.628533    3.258605    3.700201   
std      2.909699    1.305959    0.023629    0.443063    0.377714    1.503557   
min     10.590000   12.410000    0.808100    4.899000    2.630000    0.765100   
25%     12.270000   13.450000    0.856900    5.262250    2.944000    2.561500   
50%     14.355000   14.320000    0.873450    5.523500    3.237000    3.599000   
75%     17.305000   15.715000    0.887775    5.979750    3.561750    4.768750   
max     21.180000   17.250000    0.918300    6.675000    4.033000    8.456000   

               f7          t1  
count  210.000000  210.000000  
mean     5.408071    2.000000  
std      0.491480    0.818448  
min      4.519000    1.000000  
25%      5.045000    1.000000  
50%      5.223000    2.000000  
75%      5.877000    3.000000  
max      6.550000    3.000000

In [3]:
seeds['t2'] = seeds['t1']
seeds['t3'] = seeds['t1']
seeds['t1'] = seeds['t1'].apply(lambda x: 1 if x==1 else 0)
seeds['t2'] = seeds['t2'].apply(lambda x: 1 if x==2 else 0)
seeds['t3'] = seeds['t3'].apply(lambda x: 1 if x==3 else 0)
seeds.describe()

f1          f2          f3          f4          f5          f6  \
count  210.000000  210.000000  210.000000  210.000000  210.000000  210.000000   
mean    14.847524   14.559286    0.870999    5.628533    3.258605    3.700201   
std      2.909699    1.305959    0.023629    0.443063    0.377714    1.503557   
min     10.590000   12.410000    0.808100    4.899000    2.630000    0.765100   
25%     12.270000   13.450000    0.856900    5.262250    2.944000    2.561500   
50%     14.355000   14.320000    0.873450    5.523500    3.237000    3.599000   
75%     17.305000   15.715000    0.887775    5.979750    3.561750    4.768750   
max     21.180000   17.250000    0.918300    6.675000    4.033000    8.456000   

               f7          t1          t2          t3  
count  210.000000  210.000000  210.000000  210.000000  
mean     5.408071    0.333333    0.333333    0.333333  
std      0.491480    0.472531    0.472531    0.472531  
min      4.519000    0.000000    0.000000    0.000000  
25%      5.045000    0.000000    0.000000    0.000000  
50%      5.223000    0.000000    0.000000    0.000000  
75%      5.877000    1.000000    1.000000    1.000000  
max      6.550000    1.000000    1.000000    1.000000

In [4]:
seeds.head()

f1     f2      f3     f4     f5     f6     f7  t1  t2  t3
0  15.26  14.84  0.8710  5.763  3.312  2.221  5.220   1   0   0
1  14.88  14.57  0.8811  5.554  3.333  1.018  4.956   1   0   0
2  14.29  14.09  0.9050  5.291  3.337  2.699  4.825   1   0   0
3  13.84  13.94  0.8955  5.324  3.379  2.259  4.805   1   0   0
4  16.14  14.99  0.9034  5.658  3.562  1.355  5.175   1   0   0

In [5]:
min_max_scaler = preprocessing.MinMaxScaler()
seeds_scaled = min_max_scaler.fit_transform(np.array(seeds))
pd.DataFrame(seeds_scaled).describe()

0           1           2           3           4           5  \
count  210.000000  210.000000  210.000000  210.000000  210.000000  210.000000   
mean     0.402032    0.444067    0.570767    0.410773    0.448043    0.381633   
std      0.274759    0.269826    0.214423    0.249473    0.269219    0.195498   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.158640    0.214876    0.442831    0.204533    0.223806    0.233575   
50%      0.355524    0.394628    0.593013    0.351633    0.432644    0.368474   
75%      0.634089    0.682851    0.723004    0.608530    0.664113    0.520570   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

                6           7           8           9  
count  210.000000  210.000000  210.000000  210.000000  
mean     0.437751    0.333333    0.333333    0.333333  
std      0.241989    0.472531    0.472531    0.472531  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.258986    0.000000    0.000000    0.000000  
50%      0.346627    0.000000    0.000000    0.000000  
75%      0.668636    1.000000    1.000000    1.000000  
max      1.000000    1.000000    1.000000    1.000000

In [16]:
pd.DataFrame(seeds_scaled).head(5)

0         1         2         3         4         5         6    7  \
0  0.440982  0.502066  0.570780  0.486486  0.486101  0.189302  0.345150  1.0   
1  0.405099  0.446281  0.662432  0.368806  0.501069  0.032883  0.215165  1.0   
2  0.349386  0.347107  0.879310  0.220721  0.503920  0.251453  0.150665  1.0   
3  0.306893  0.316116  0.793103  0.239302  0.533856  0.194243  0.140817  1.0   
4  0.524079  0.533058  0.864791  0.427365  0.664291  0.076701  0.322994  1.0   

     8    9  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0

In [25]:
# train network
from neuron_network import NeuronNetwork

network = NeuronNetwork(7, 0.5)
network.add_layer(10)
network.add_layer(5)
network.add_layer(5)
network.add_layer(3)

expected = seeds_scaled[0][7:10]
expected

for epoch in range(2000):
    for tr in range(210):
        
        expected = np.array(seeds_scaled[tr][7:10])
       
        inputs = np.array(seeds_scaled[tr][0:7])
        output = network.feed(inputs)
        network.backpropagate_error(expected)
        network.update_weights()
    
print(np.array(seeds_scaled[4][7:10]))
print(network.feed(np.array(seeds_scaled[4][0:7])))


[ 1.  0.  0.]
[ 0.99492804  0.00347284  0.00521049]


In [24]:
# print(network)

print(np.array(seeds_scaled[200][7:10]))
print(network.feed(np.array(seeds_scaled[200][0:7])))

[ 1.  0.  0.]
[ 0.99777224  0.00125703  0.00141362]


In [26]:
sumTrue = 0
errors = np.array([])
count = 0
for i in range(147,210):
    count +=1
    inputs = np.array(seeds_scaled[i][0:7])
    raw_output = network.feed(inputs)
    output = [(1.0 if x > 0.5 else 0.0) for x in raw_output.tolist()]
    expected = np.array(seeds_scaled[i][7:10])

    errors = np.append(errors, np.sum(np.abs(expected - raw_output)))
#     print(output, expected)
    if output[0] == expected[0] and output[1] == expected[1] and output[2] == expected[2]  :
        sumTrue += 1
        
#     if expected == 1:
#         print(i)

precision = sumTrue / count
promError = np.mean(np.abs(errors))
print('prec: ', str(precision), 'error: ', str(promError))

prec:  1.0 error:  0.00873873402866


In [31]:
seeds_scaled.shape

(210, 10)

In [32]:
print(network)

neuron: [ 0.16147309  0.19214876  0.54718693  0.19369369  0.24518888  0.63346292
  0.26784835]
{ 
	{ 8.70803872228 9.89847830358 -2.11902936749 8.86046148483 7.78927929291 1.87054608312 -8.90920307035 } b: -5.84048252089 z: -1.26722703487 o: 0.219732307512 d:-3.1384150637e-09
	{ 2.56506314816 -0.805013765619 6.93903151717 -26.4677347045 4.15152763492 12.0583338081 21.0365557149 } b: -10.0056284726 z: 3.21521442563 o: 0.961402825705 d:7.894512761e-09
	{ 5.81827863617 4.53437198455 7.99942890335 2.90564336137 6.77126922364 -5.53437865562 -18.665316332 } b: -1.24300677389 z: -1.3373075924 o: 0.20795317269 d:-2.1622947487e-08
	{ 9.61992992923 8.52061772783 -7.48703221887 -10.1765956561 3.03823006951 7.77339013459 15.3481890895 } b: -13.3027347831 z: -6.40001565248 o: 0.00165877515909 d:1.33196308239e-10
	{ 3.20538849941 5.0071665253 -0.515713610853 4.78747372582 4.21104519499 -0.560673084913 -6.63675187008 } b: -3.55342717938 z: -2.52891783372 o: 0.0738556337086 d:-1.05188740626e-10
	{ -3.